mit-dci/lit

- lit.go
- uspv/eight333.go
This PR is to create lit home directory.
Default directory is `$HOME/.lit` and can be changed by `lit` command option `-dir`.
> Add lit home directory to store files such as headers.bin

- cmd/lit-af/chancmds.go
- cmd/lit-af/netcmds.go
- cmd/lit-af/shell.go
- cmd/lit-af/walletcmds.go
Added `help <cmd>` | `<cmd> -h` support, with some TODO entries for commands I don't fully understand myself.
> help <cmd> | <cmd> -h

- cmd/lit-af/autocomplete.go
Fixes bug where the same peer would be listed multiple times in autocomplete for closed peers.
> [bug-fix] Same peer listed multiple times in autocomplete for closed peers

- uspv/hardmode.go
`BlockRootOK checks for...` but function name is `BlockOK`.
> Trivial: Fix comment.

- cmd/lit-af/lit-af.go
- cmd/lit-af/shell.go
- lit.go
- litrpc/listener.go
previously, the RPC was json-rpc over a regular TCP connection.
This is nice and simple, but the problem is that browsers and web stuff generally can't make TCP connections.  They can make websocket connections though, which as far as I can tell are pretty much the same as TCP in that it's just bi-directional data.
This PR changes litrpc and lit-af so that they both use websockets.  It's acutally a bit of overhead in that it's a TCP connection, then an HTTP connection, then a websockets connection, THEN the json-rpc goes back and forth.  In practice the code is minimal though and libraries are in "x" which hopefully won't change, and maybe get put into the standard library.
Could also use some HTTP / websocket based auth methods in the future.  (still no RPC auth at all)
> Switch to websocket based RPC connection

- .travis.yml
This PR adds Travis support. Currently, all Travis will do is build lit and run the unit tests. Future PRs should:
- add integration tests to be run by Travis
- add code coverage
- etc
@adiabat - to get this to run, you'll need to open an mit-dci travis account (free for open source projects), and then update the settings to do CI on the lit project. You'll also need to enable Travis on the github side from the mit-dci/lit repository settings → Integration and services → services if you want Travis to run on PRs.
Travis runs currently fail the unit tests due to #44
> Add minimal Travis support

- cmd/litpy/litrpc.py
- cmd/litpy/test_lit.py
Adds a `__getattr__()` method to LitConnection, which
returns a closure on `send_message()`. Lit RPC commands can now be called
directly on LitConnection, without the need to add methods for each new
RPC.
> Lit connection dispatcher

- cmd/litpy/test_lit.py
test_lit.py now starts two nodes and tests the Listen() and Connect() RPCs.
Also adds a LitNode class to test_lit.py.
Builds on #52 - only the _[tests] add LitNode class to test_lit.py_ and _[tests] test Listen and Connect_ commits are for review in this PR.
> [tests] test Listen and Connect RPCs 

- .travis.yml
- cmd/litpy/litrpc.py
- test/bcnode.py
- test/litnode.py
- test/test_lit.py
A bunch of improvements:
- refactor BCNode, LCNode and LitNode into their own modules
- Add copyright notice and use `#!/usr/bin/env python3` hashbang instead of `#!/usr/bin/python3` for portability
- check that bitcoind version is >0.14 and litecoind version is >0.13.2
- fix build/test in travis
- cache bitcoind and litecoind in travis to avoid slow downloads
- improve logging on failure
- make sure bitcoind and lit processes are cleaned up at the end of the test
Some of these commits are broken until the `[tests] fixups` commit, but I'm not going to bother rearranging them since I expect you'll merge this as a single commit.
> Fix and improve tests

- .travis.yml
- test/README.md
- test/lit_test_framework.py
- test/test_basic.py
This moves the test framework into its own lit_test_framework module, to be imported and subclassed by indvidual test scripts.
There is currently only one test script: test_basic.py. Additional tests named `test_[description].py` can be added.
This splits the test logic from the test framework so additional tests can be added and worked on in parallel.
README updated to describe the new structure.
> Test framework

- lit.go
- test/README.md
- test/bcnode.py
- test/combine_logs.py
- test/combined_log_template.html
- changes lit to log microseconds
- changes bitcoind config in test framework to log microseconds
- adds combine_logs tool for combining logs from multiple lit nodes and bitcoind nodes. Output looks like:
(once logging has been added to the test framework, those logs will also be included in the combined log)
> Improved logging

- cmd/lit-af/shell.go
- cmd/lit-af/walletcmds.go
- litrpc/walletcmds.go
- qln/basewallet.go
- qln/fund.go
- wallit/basewalletif.go
This isn't a good long term solution, but for now it helps to be able to manually set fee rates.
There's a new RPC command SetFee which lets you set a fee rate (satoshis per byte) for any wallet.  If you give it a negative number, it won't change the fee rate.  It always returns the current fee rate.
(So if you want to just check what the fee rate is, send -1)
The corresponding command has been added to lit-af.
> Add SetFee RPC command

- .travis.yml
- cmd/litpy/litrpc.py
- test/bcnode.py
- test/combine_logs.py
- test/lit_test_framework.py
- test/litnode.py
- test/test_lc.py
- wallit/init.go
Adds a test for litecoin. At the moment, this is almost a duplicate of the test_basic test. In the future it'd be nice to refactor into a single test. An argument would be passed into the test to specify which chain should be used (or a list of chains in the case where we're testing multiple chains).
There are a few odds and ends in here as well - attaching a debugger, testing whether any of the required binaries are already running when the test starts, and cleaning up the temp directory after a test run.
Still a work in progress. Travis is failing to build this correctly. I can't tell why.
> [wip] Test litecoin

- .travis.yml
golang imports are all absolute rather than relative, so if you fork a repo then all of your imports are pointing to the forked-from repo rather than your own repo.
This isn't a problem locally - you clone the forked-from repo and then add your forked repo as a new remote. However, when you push a branch to github, travis will clone from *your* forked repo, and will then download import from the forked-from repo.
I think this is fixed by setting the `go_import_path` in travis. That causes travis to clone from your forked repository into `$GOPATH/src/<go_import_path>`, so when go comes to import the packages, it already has them in the right place.
This is what was causing https://github.com/mit-dci/lit/pull/72#issuecomment-301909049 to fail for my travis, but not the travis PR build.
> [ci] Update travis for forked repos

- .travis.yml
- coinparam/bc2.go
- coinparam/bitcoin.go
- coinparam/litecoin.go
- coinparam/register.go
- lit.go
- litrpc/walletcmds.go
- qln/basewallet.go
- qln/init.go
- uspv/chainhook.go
- uspv/header.go
- uspv/init.go
- uspv/msghandler.go
- uspv/spvcon.go
- wallit/basewalletif.go
- wallit/chainhook.go
- wallit/init.go
- wallit/wallit.go
We've extended a fork of the btcsuite package, but it's getting hard to manage.
This brings the coin parameter libraries into lit.  It's organized so that adding a new coin will just be one .go file for everything (network bytes, params, genesis info)
Also can't use btcutil address structs, but had nearly stopped using those anyway.
> Move parameters from btcsuite/chaincfg to lit/coinparam

- coinparam/bc2.go
- coinparam/bitcoin.go
- coinparam/difficulty.go
- coinparam/litecoin.go
- coinparam/register.go
- coinparam/vertcoin.go
- lit.go
- qln/init.go
- uspv/chainhook.go
- uspv/eight333.go
- uspv/hardmode.go
- uspv/header.go
- uspv/msghandler.go
- wallit/dbio.go
- wallit/init.go
- wallit/wallit.go
Most of the diffs here are in uspv, changing the headers code.  Previously the flow was:
- get a block inv message
- request headers
- get a headers message
- append all those headers onto the headers.bin file
- verify the validity and work of newly appended headers
- if something goes wrong, basically just choke
This was simple and worked OK for test networks, but reorgs *do* happen.
New flow
- get headers message, but keep them in RAM, not on disk
- grab on-disk headers back to the last diff adjust, prepend in RAM
- the header validity check function takes the in-RAM headers, and checks them
- if the headers are OK, write them to disk
This allows reorgs to happen within a single headers message.  Headers messages are limited to 2000 headers, so this does not support reorgs deeper than …
> Update uspv and wallit to recognize chain reorgs

- .travis.yml
- test/lit_test_framework.py
- test/litnode.py
- test/test_basic.py
- test/utils.py
Fixes some issues that were preventing Travis from running successfully:
- `pip install` now needs to be `sudo pip install`.
- remove dumb `time.sleep()` calls and use `wait_until()` to ensure lit nodes are sync'ed to blockchain tip.
- use `assert_equals()` in tests for easier debugging
- temporarily disable litecoin tests.
Thanks to @Varunram for motivating me to fix this and giving some pointers!
> Fix travis

- lit.conf
- lit.go
- lndc/lnadr.go
- qln/init.go
- qln/lndb.go
- qln/netio.go
- qln/tracker.go
Uses this simple node.js script (https://github.com/metalicjames/lit-tracker) to announce its LN address and IP signed by its public key. The server can be configured using the `tracker` option in the config file.
> Implement LN node tracker for IP-less connection

- lit.go
1. --help no longer prints twice
Remove fmt. statements and use log. wherever appropriate
Incorrect args now show "Use ./lit -h to show usage"
2. Creating a config file at new home directories does not require a sample lit.conf
> Cleanup lit.go

- Dockerfile
I built a Dockerfile to be able to run LIT as a docker container. Not sure if this is something you guys see use for, but it makes it quite easy to run the LIT daemon on server/embedded Linux environments that are able to use docker.
What it currently does is it runs go get on the original repo to get the prerequisites and then copies in the source code files from the working directory. You could remove lines 8 and 9 to simply have it build a container out of the active master branch.
> Dockerized LIT for easy portability

- lit.conf
Since we now handle conf stuff in lit.go, doesn't make sense to have this hanging around.
> Remove lit.conf since we auto generate conf file

- cmd/lit-af/chancmds.go
- cmd/lit-af/shell.go
- litrpc/chancmds.go
- lnutil/msglib.go
- qln/justicetx.go
- qln/lnchannels.go
- qln/pushpull.go
- qln/serdes.go
This pull request adds an extra parameter to the channel push command so you can include a 32 byte data payload with the push. This allows recipients so associate a payment with a data payload that is communicated out-of-band. 
It also include a `history` RPC and `lit-af` command to allow users to see the data payload for each push, as well as their relative amounts.
These changes breaks existing databases so you'll need a new one (delete `ln.db`).
> Include data with push command, and provide a history command to view previous payments

- cmd/lit-af/chancmds.go
- cmd/lit-af/shell.go
- litrpc/chancmds.go
- lnutil/msglib.go
- lnutil/msglib_test.go
- qln/fund.go
- qln/lndb.go
Similarly to this PR: https://github.com/mit-dci/lit/pull/136, add a data field to the fund command.
This change does not break existing databases but is not backwards compatible protocol-wise.
> Add data field to fund operation

- cmd/lit-af/netcmds.go
- cmd/lit-af/shell.go
- litrpc/netcmds.go
- lnutil/msglib.go
- qln/init.go
- qln/lndb.go
- qln/msghandler.go
- qln/routing.go
This PR implements a form of Link-State routing for Lit. Peers send each other information about their open and connected channels periodically and rebroadcast such advertisements from other peers. This allows each Lit node to build its own channel graph. Once multi-hop is implemented, this graph could be used in conjunction with Dijkstra's algorithm to find a route for a payment. 
This also adds the command `graph` to `lit-af` which dumps a Graphviz DOT encoded version of the channel graph. e.g. ![image 1](https://user-images.githubusercontent.com/4153717/35706694-b97f2f82-0774-11e8-916d-b01924d1a978.png)
> Basic Link-State channel graph generation

- Dockerfile
Implemented a two-stage build so that the final Docker image does not have the full Golang stack on it. Image size went from ~550MB to ~30MB
> Optimized docker image size 

- lit.go
- litrpc/listener.go
When trying to run coordinated tests by talking to two LIT instances running in Docker via RPC, it's necessary to connect to the RPC from a remote machine. Since localhost was hardcoded, this was not possible. I added a configuration option for rpchost, that defaults to the (current) localhost, but allows you to set it to 0.0.0.0.
> Allows configuring the host to listen for RPC connections

- Dockerfile
Plain Alpine is missing SSL root CA's, therefore doing a HTTPS request from within the container will not work. Ran into this when working with Oracles (will probably also affect the tracker). This change to the Dockerfile fixes that issue.
> Adds CA Roots to docker container. Can't use HTTPS without it

- cmd/lit-af/dlccmds.go
- cmd/lit-af/shell.go
- dlc/contract.go
- dlc/dlcdb.go
- dlc/manager.go
- dlc/oracle.go
- litrpc/dlccmds.go
- litrpc/listener.go
- lnutil/dlclib.go
- lnutil/msglib.go
- qln/basewallet.go
- qln/dlc.go
- qln/init.go
- qln/lndb.go
- qln/magicnums.go
- qln/msghandler.go
- qln/signtx.go
- wallit/signsend.go
This first version allows peers to import oracles, create new contracts, offer them to peers, accept/decline, and settle. It also watches the blockchain for settlements by others to claim the correct outputs back to the wallit.
> First version of Discreet Log Contracts

- wallit/signsend.go
If there were a mixture of witness and non-witness outputs in the db then PickUtxos would sometimes select non-witness inputs even when only-witness was set. This prevented channel funding in a number of cases.
> Fix bug where non-witness outputs were selected in PickUtxos

- cmd/lit-af/chancmds.go
- cmd/lit-af/dlccmds.go
- litinit.go
- qln/buildtx.go
- qln/pushpull.go
- uspv/init.go
- uspv/msghandler.go
- watchtower/justice.go
- watchtower/watchdb.go
Mostly problems with misuse of `Printf` and `Println`. This PR is required to make the tests/build pass.
> Fix a bunch of compile errors when running go tests

- qln/init.go
When a channel is first funded your refund address is registered with wallit so the resulting UTXO is picked up by a close. After Lit was restarted we were not re-registering those refund addresses with the wallit. As a result, closing a channel resulted in you receiving no new UTXO.
> Re-register refund addresses with wallit after restarting lit

- qln/init.go
Similarly to wallet addresses, upon restarting lit channel outpoints were forgotten. This meant that restarting lit before a channel was confirmed meant that it would never be confirmed.
> Re-register channel outpoints on restart

- lit.go
ni.media.mit.edu has been down for a while. Hubris is hosting a tracker now instead.
> Use a tracker that is online

- qln/lnchannels.go
- qln/msghandler.go
- qln/pushpull.go
Some handlers would run while others were in-flight meaning that the channel state got messed up. Add an extra mutex to `Qchan` to ensure only one message handler runs at a time. 
This also means rather than erroring out when the channel is busy, we can now make colliding pushes that resolve simultanous pushes.
This PR also adds a bunch of useful logging to the pushpull code.
> Fix race condition in pushpull code to allow colliding pushes

- qln/pushpull.go
If `lit` is interrupted during channel activities, recovering the channel causes a deadlock due to consecutive pushes into `ClearToSend`. Also ensure pushes into CTS are done with the `ChanMtx` held.
> Fix one observed and one potential deadlock

- lit.go
- qln/autoconnect.go
- qln/init.go
This pull request will allow lit to automatically start listening on a configurable port (default 2448), and periodically reconnect to peers it knows, in case their connection dropped. Interval for re-connection is configurable, default is 1 minute.
So when you restart LIT, it will automatically be listening for incoming connections and re-connect to peers it previously was connected to. For keeping up a network of channels, this is highly preferable over having to manually do all this.
> Automatic re-connection

- powless/nsight.go
block explorer is basically a fork of insight's API, block explorer is not well maintained now, although insight is, so we can shift to insight with the same endpoints.
> use insight api instead of blockexplorer

- lit.go
- lndc/conn.go
- lndc/lndc_test.go
- qln/init.go
- qln/lndb.go
- qln/netio.go
- qln/tracker.go
With this PR you can specify a SOCKS5 proxy with the --proxy option to Lit. Currently connections to full nodes and powless APIs still take place via the normal network. When the proxy is enabled Lit does not attempt to announce itself on the tracker and uses the proxy for tracker lookups.
> Optional SOCKS5 for LNDC connections

- qln/netio.go
- qln/tracker.go
Sometimes our default interface is IPv6, and Lit currently cannot connect to IPv6 nodes. Therefore I updated lit-tracker to accept both an IPv4 and IPv6 address on announce. This update sends both types of IP address to the tracker if available, but only attempts to connect to the IPv4 version for now. LNDC needs to be updated to handle IPv6 to use the other address potentially returned by the tracker.
> Handle updates to the tracker for IPv6 support

- lndc/conn.go
- qln/netio.go
- qln/tracker.go
- uspv/chainhook.go
- uspv/init.go
Built upon #200, functions are a bit ugly, could move them to `lnutil` if need be. View https://github.com/mit-dci/lit/commit/55249ed5517bf32820945eb5be47791ff477938b for standalone changes via this PR.
> Add ipv6 to lndc and uspv

- qln/fund.go
- test/test_basic.py
- test/test_break.py
Don't let users fund channels that are impossible to close by using an initial send less than the minOutput value or where their own balance is similarly too low. 
In the future we might want to allow "top-heavy" channels that only have one output so that channels with 0 balance on one side can still be closed.
> Enforce minOutput rules in fund

- README.md
We no longer trigger coveralls, although I guess this can be done if we install the plugin on the jenkins server once we have more tests. Might be combined along with #210
> Remove coveralls icon ; add jenkins icon

- snap/snapcraft.yaml
This package will let you publish the latest lit in the Ubuntu store, and from there reach many users on all the supported Ubuntu versions, and more Linux distributions in progress. You just have to go to https://build.snapcraft.io and enable the automated continuous delivery.
> Add the packaging metadata to build the lit snap

- sig64/sigcompress.go
- sig64/sigcompress_test.go
Signature of the special transaction is short size.
I fixed that problem , and added test case.
Signature before fixed :
3041021e0a15f55034e27e85003ca2e970d2325162592186975d29fc49b4ee24eb36021f4944c8cf4db9765d8226686ae7e9407e7a384d58b50ca786b40ddad23a6b8601
Error message before fixed :
Can't compress; sig length is 67
> Fix the problem when short signature

- uspv/init.go
- wallit/init.go
Delete one rogue `log.Println`message and modify another one. In most cases, the log reads 
```
DB height 1325523
DB height 1325523
```
and in the event of resync, something like 
```
DB height 1325523
DB height 1300000
```
which is somewhat weird.
> [trivial] edit log messages

- cmd/lit-af/chancmds.go
- cmd/lit-af/dlccmds.go
- cmd/lit-af/netcmds.go
- cmd/lit-af/walletcmds.go
Earlier, we didn't have a way whether we should stop execution, instead we relied on the code that follow to do that for us. But this caused side effects like that in #231, which should now be solved with the introduction of this bool.
> Add stopEx bool to CheckHelpCommand

- coinparam/difficulty.go
- uspv/header.go
Dodges the zero header bit bug (no problem in reorg code / our side, the incoming headers themselves have this set to 0, dunno why) and fixed a bug where you can't join the chain after a deep re-org. Also removed some noob error statements.
> Bugfixes for testnet

- qln/msghandler.go
- watchtower/watchdb.go
Earlier nodes could remotely shut down a non tower peer peer by sending them tower messages. Now, we just ignore those messages. We could store it in some local db and give it to them for niceness (since they don't know we aren't a watchtower and we don't / can't tell them right now).
> Don't do anything if we don't enable --tower

- powless/nsight.go
- qln/tracker.go
This is the reason that many RPC calls were timing out and also the cause for frenzied discussions on related issues.
> Timeout external API calls before the RPC timeout

- qln/htlc.go
When searching for the desired htlcTxo in a commitment transaction, if it wasn't found it returned nil. Instead return an error and check for it to stop the nil pointer dereference
```
2018/07/31 20:42:26.764116 Generating offer HTLC with localPub [02a810776fa2aaab630ce39ee6aa1c865cc34a82fc9f993f27c8bfb49639d896a6] and remotePub [02486fdc31e81e0f856c945fa24bc966ba57578637921ac78b5706f6e36b477cb7]
2018/07/31 20:42:26.764322 HTLC 0, script: 76a9144456ff83ba271edbe7099a1273188ab630d9167d8763ac672102486fdc31e81e0f856c945fa24bc966ba57578637921ac78b5706f6e36b477cb77c8260876475527c2102a810776fa2aaab630ce39ee6aa1c865cc34a82fc9f993f27c8bfb49639d896a652ae67a82086a1c25150ce1677025e0275e434de2c0c2eb598864cf4976e12df973326cceb88ac6868, myBase: …
```
> Fix segfault caused by nil htlcTxo

- cmd/lit-af/shell.go
- lnutil/color.go
Reformats the channel list in lit-af, splits it up in four categories:
- Open
- Unconfirmed (awaiting block confs)
- Closed
- Disabled (coin daemon not connected)
Rework of #292
> Reformat channel list in lit-af

- qln/dualfund.go
- qln/fund.go
Usage of the new const was not consistent throughout, causing an asymmetry in the commitment TX and thus signature errors.
Fixes #343
> Fee asymmetry error

- lit.go
- qln/autoconnect.go
Autolisten is needed for lit-af now we're talking to lit over LNDC. So autoReconnect should be on by default (which will also initiate listening).
Also added some logging in case something goes wrong, because now it's not obvious.
> Autolisten fixes

- cmd/lit-af/shell.go
This fixes failure in `go test`:
```
cmd/lit-af/shell.go:21: Sprintf call needs 9 args but has 10 args
```
> Fix test failure

- lndc/noise_test.go
- qln/lndb.go
- qln/multihop.go
- shortaddr/shortadr.go
This fixes the `Not connected to cointype 5` issue in one of the tests. 
Magic numbers...
Also added a few import changes that were causing the build to fail. Wrong packages were imported.
> Fix for (de)serialization error

- test/tests.txt
These two tests should not run until there's a fix for allowing to break a channel right after funding.
> Re-disabled tests for break right after fund, since it's not supported

- qln/break.go
- test/tests.txt
This fixes the failing two tests breaking right after fund. The elkrem is empty, but also not needed to break. Elkrem is needed for justice - at state 2 or higher.
Return value of ElkRcv is not used, but it used to crash this section.
Re-enabled the two tests
> Just remove obsolete logging statements. Elkrem not needed for break

- lit.go
- litinit.go
- logging/log.go
Instead of `-v`, `-vv`, `-vvv`, `-vvvv` and `-vvvvv`, we now make `LogLevelError` as default (which makes sense because you shouldn't ideally ignore any errors) and then have `LogLevelWarning` as `-v`, `LogLevelInfo` as `-vv` and `LogLevelDebug` as `-d` or `--debug`.
> Change logging scheme

- uspv/init.go
This allows you to connect to coindaemons not just by IP or `localhost` but also hostname. So i could use `reg=someserver:18444`
> Allow connecting to coindaemon peers by hostname, not just localhost

- cmd/lit-af/chancmds.go
- cmd/lit-af/netcmds.go
Was earlier
```
rcauth <pub> <auth (true|false)>
Manages authorization for remote controlrcreq
Requests remote control authorizationhistory
Show all the metadata for justice txs.
off	Shut down the lit node.
```
now is 
```
rcauth <pub> <auth (true|false)>
Manages authorization for remote control
rcreq
Requests remote control authorization
history
Show all the metadata for justice txs.
```
> Format lit-af help output

- qln/msghandler.go
Message handlers for multihop payments were missing from the refactored code. Added them back in this PR.
> Multihop message handlers

- lnp2p/peermgr.go
- qln/init.go
The new peer-to-peer code was missing the ability to lookup node addresses via the tracker. I've added that in this PR. Needed also for convenient multihop payments, otherwise you have to manually connect to the nodes you want to pay beforehand.
> Use tracker to lookup nodes (new p2p code)

- qln/remotecontrol.go
The refactored peer-to-peer code uses a different indexing for the peers. It does contain logic to translate to the old indexing, but message handlers receive two indexes:
- `msg.Peer()` (this is the "new" index)
- `peer.Idx` (this is the "old" index)
`peer` is the second parameter to a message handler (of type `RemotePeer`). This index can also be used as index to `nd.RemoteCons`.
The problem is, that when sending a message, the `nd.tmpSendLitMsg` expects the message.Peer() to be an _old_ index. So if you pass that `msg.Peer()` it will _only_ work when the old and new indexes are the same. 
This manifests itself when a peer reconnects to you. It will receive a new index in the new system, but reuse its old index in the old system. 
By switching to the old indexing (using the `peer.Idx`) …
> Mismatch between peer.Idx and msg.Peer() after refactor

- lit.go
- qln/remotecontrol.go
- uspv/chainhook.go
- uspv/eight333.go
- uspv/init.go
This was the default behaviour before recent PRs. This PR also adds a timeout for connecting to external peers instead of waiting indefinitely for non proxy connections. This also closes a bug with testnet start heights which earlier would have produced:
```
testnet3 birth height give as 0, but parameters start at 1255968
```
but now stands corrected.
> Allow lit node to run even if no daemon is running

- cmd/lit-af/netcmds.go
Something weird happened when @Varunram changed ports to be numerical that caused things to not compile.  But it works fine now, I think.
> Fixed typing and local variable definitions in Lit-AF

- litrpc/lndcrpcclient.go
When you use an LndcRpcClient, you can't close the connection. While building some utilities that interface with lit this becomes kind of problematic.
> Allow closing LNDC RPC client

- litrpc/lndcrpcclient.go
When receiving a reply at the same time of sending a request, you will concurrently write to the map which should not happen. This fixes that.
> Add mutex for modification of the map tracking request/reply

- db/lnbolt/peerdb.go
- lit.go
- lncore/peers.go
- lnp2p/listen.go
- lnp2p/peermgr.go
- qln/eventhandlers.go
- qln/netio.go
- test/itest_break.py
- test/itest_close.py
- test/itest_pushbreak.py
- test/itest_pushclose.py
- test/itest_reconnect.py
- test/runtests.py
- test/testlib.py
- test/tests.txt
I don't think that I need to restart the node that's reconnecting to the other nodes, but that was the simplest idea I had to make sure that the nodes would actually disconnect.
I also had to refactor a bit of the testlib code to get it to support dynamically starting/shutting down nodes on demand.
> Fixed peerIdx confusion after reconnecting/restarting nodes, with tests

- elkrem/elkrem.go
- elkrem/elkrem_test.go
- elkrem/serdes.go
- elkrem/serdes_test.go
- litrpc/chancmds.go
- qln/close.go
- qln/init.go
- qln/justicetx.go
- qln/lnchannels.go
- qln/lndb.go
- qln/magicnums.go
- qln/pushpull.go
- qln/serdes.go
- qln/signtx.go
- test/test_combinators.py
- test/testlib.py
- test/tests.txt
This is a preliminary step towards the new storage layer and channel management code.  It *also* makes channel serialization a lot simpler and less prone to breakage, and in the process I removed a few hundred lines of very scary code.
> Refactor Qchan serialization to store data as flat JSON

- coinparam/dummyusd.go
The difficulty adjustment for dummy USD is non-existent. It's always the minimum since it's a regtest copy. Without this it won't sync past block 2015
> Fixes difficulty adjustment for dummy USD regtest (there is none)

- lit.go
- litinit.go
- lnutil/keyfile.go
- qln/routing.go
- test/testlib.py
We don't complain about perfectly normal things now, like not finding the config file.  I also added an envvar called `LIT_KEYFILE_WARN` that if `0` will suppress the warning about having an unencrypted `privkey.hex`.
> Added more graceful handling to some errors on startup

- cmd/lit-af/lit-af.go
- litinit.go
- logging/log.go
Used the same `flags` package like we do for `lit` since its more extensible and can host arrays.
ref: #425.
> Improve lit-af command line arg parsing

- lnp2p/peermgr.go
- qln/remotecontrol.go
Still investigating why peerIds start from 0
ref: #414
> Fix bug where any remote RPC call crashes lit

- db/lnbolt/peerdb.go
- litrpc/netcmds.go
- lncore/peers.go
- lnp2p/listen.go
- lnp2p/peermgr.go
- lnp2p/util.go
- qln/init.go
- qln/netio.go
This unifies the setup we do *after* we've established the connection.  I moved the peer init code from the functions for connecting to peers and for listening for new connections to another function so new connections get the same treatment regardless of how it was created.
I also did some changes to the NetSettings struct, it's passed to the peermgr on creation, so we don't have to provide it every time we connect to a peer.  Plus some other minor fixes there.
I also added a `lncore.ParseLnAddr` function that takes a string, verifies that it conforms to what we expect for a lit address, and returns it as a `LnAddr` or returns an error describing why it isn't valid.  I also replaced all of the direct casts to `lncore.LnAddr` across lit to calls to that function.  There's also a …
> Made some changes to peer init in lnp2p

- coinparam/vertcoin.go
Another tiny fix, [from this line in vertcoin-core](https://github.com/vertcoin-project/vertcoin-core/blob/0f495ed667f04641a728b507fc8326fa9eb1d47b/src/chainparams.cpp#L329).
> Address prefix fix

- README.md
- WALKTHROUGH.md
- cmd/lit-af/lit-af.go
- docs/test-setup.md
- lit.go
Now you can run the lit-af for several instances of a lit on single machine as:
./lit-af --litHomeDir=/path/to/lit1 --autoListenPort=2448
./lit-af --litHomeDir=/path/to/lit2 --autoListenPort=2449
> lit-af fix for multiple lit instances on single computer.
