mit-dci/lit

- cmd/lit-af/chancmds.go
- shell.go
Fix some old style help of subcommands in lit-af.
> Fix helps of lit-af

- cmd/lit-af/autocomplete.go
- cmd/lit-af/lit-af.go
Uses https://github.com/chzyer/readline -- not sure if it's the best option as I didn't do much research but it may be good for now.
> Add readline support to lit-af

- cmd/lit-af/chancmds.go
- cmd/lit-af/lit-af.go
- cmd/lit-af/netcmds.go
- cmd/lit-af/shell.go
- cmd/lit-af/walletcmds.go
- lnutil/color.go
- qln/msghandler.go
- qln/pushpull.go
I may have gone a bit overboard, but time will tell. 
I am colorizing all satoshi outputs in the following manner:
- BTC values are white + bold,
- mBTC values are regular,
- <1mBTC values are grayish (faint).
It feels like it expresses amounts in a easy to comprehend manner, but I am open to changing. :)
> Colorize methods and outputs.

- cmd/lit-af/lit-af.go
- cmd/lit-af/shell.go
- cmd/lit-af/walletcmds.go
- lnutil/color.go
Also added some more colors (addresses & outpoints).
> Renamed color vars to their purpose, rather than their colors.

- lnutil/btclib_test.go
This is an unit-test for lnutil/btclib.go.
There are some TODOs but I add them later.
> Add unit-test for btclib.go

- lnutil/curvelib_test.go
I found two panic points but I think its priority might be low.
If no needs to fix them, I delete TODOs for the points and push again.
> Add unit-test for curvelib.go

- .gitignore
- cmd/lit-af/chancmds.go
- cmd/lit-af/lit-af.go
- cmd/lit-af/netcmds.go
- cmd/lit-af/shell.go
- cmd/lit-af/walletcmds.go
- lit.go
> Windows color fix

- lnutil/lnlib_test.go
This is an unit-test for lnlib.go.
If something to modify, please let me know.
> Add unit-test for lnlib.go in lnutil

- cmd/litpy/README.md
- cmd/litpy/litrpc.py
This PR refactors the litpy functions into a LitConnection class.
Several other cleanups, including adding a README and fixing the PEP8 warnings from flake8.
> Cleanup litpy

- .travis.yml
- cmd/litpy/litrpc.py
- cmd/litpy/test_lit.py
Very basic for now - starts a lit node, creates an address, checks the balance and shuts down the node.
This at least builds and runs a lit node in CI. That should catch any egregious errors that cause lit to fail to start.
More thorough testing can be added later.
> Add integration test and run in travis

- litbamf/client/js/Channels.js
- litbamf/client/js/Globals.js
- litbamf/client/js/Legacy.js
- litbamf/client/js/MetaCmds.js
- litbamf/client/js/NetCmds.js
- litbamf/client/js/Overview.js
- litbamf/client/js/main.js
- litbamf/client/sass/channels.scss
- litbamf/client/sass/globals.scss
- litbamf/client/sass/legacy.scss
- litbamf/client/sass/vendor/modal/LICENSE.md
- litbamf/client/sass/vendor/modal/animations.css
- litbamf/client/sass/vendor/modal/config.css
- litbamf/client/sass/vendor/modal/core.css
- litbamf/client/sass/vendor/modal/index.css
- litbamf/client/sass/vendor/modal/theme.css
- litbamf/public/index.html
- litrpc/netcmds.go
- qln/lndb.go
- qln/magicnums.go
- qln/netio.go
> Lit bamf channels page

- .travis.yml
- cmd/litpy/test_lit.py
- test/README.md
- test/litpy
- test/test_lit.py
General improvements to test_lit:
- I've incorporated @vinchang2015's new receive test case.
- added litecoin support in anticipation of multichain wallit support
- moved the integration test into its own base directory
notes:
- travis doesn't like me at the moment (I assume because this has triggered a bitcoin mining flag). I've emailed them to re-enable my account. Don't be surprised if Travis refuses to build this PR.
- this seems a little flakey - sometimes the receive funds fails. I haven't dug into why that is
This should replace #54 since it contains a superset of the functionality in that PR.
> test_lit.py improvements

- test/lit_test_framework.py
- test/litnode.py
- test/test_basic.py
Updates the basic test to:
- open a channel between two nodes
- push funds one way
- push funds back
- close the channel
> [tests] Add channel tests

- cmd/litpy/litrpc.py
- test/bcnode.py
- test/combine_logs.py
- test/lit_test_framework.py
- test/litnode.py
- test/test_basic.py
Implements python logging in the test framework.
Running a test with standard logging:
Running a test with debug logging:
Using combine_logs tool to combine test_framework/bitcoind/lit logs:
> Test logging

- cmd/litpy/litrpc.py
- test/bcnode.py
- test/combine_logs.py
- test/lit_test_framework.py
- test/litnode.py
- test/test_basic.py
Various cleanups for the test framework:
- helper methods in the test framework to start bitcoind and lit nodes
- helper log_balanes() and log_channel_balance() methods
- small cleanups
Builds on top of #68
> [tests] Various cleanups

- cmd/lit-af/shell.go
- cmd/lit-af/walletcmds.go
- litrpc/walletcmds.go
- qln/basewallet.go
- qln/fund.go
- wallit/basewalletif.go
Adds explicit getter and setter functions for fee. Follows #71
> [rpc] add Fee() and SetFee() rpcs

- .travis.yml
- test/lit_test_framework.py
- test/litnode.py
- test/test_basic.py
- test/test_break.py
Add a new test that breaks a channel:
- setup, create channel, send funds around
- node0 breaks channel
- assert node0 has funds but can't spend, node1 has funds and can spend
- advance 5 blocks
- assert node0 and node1 can both spend funds
> [tests] break channel

- litrpc/walletcmds.go
- test/test_basic.py
ChanTotal currently includes the channel balance for channels that are closed. Don't do that.
> [rpcs] Better ChanTotal in Balance()

- lit.conf
- lit.go
This PR aims to accomplish config file parsing to some extent. As of now, it can parse params in `config/`. Will keep constantly updating this branch under @adiabat's suggestions and inputs.
> Basic Config File Parsing

- lit.go
Deep Apologies for missing this as I was testing. Rearranged the config parsing stuff and removed one redundant variable and piece of code.
> Give preference to CLI params

- qln/lndb.go
Correct chanel to channel. I could combine this with the Seeds PR too, your call :)
> Small typo over at qln/lndb.go

- README.md
File: https://github.com/sudheesh001/lit/blob/bdfdbd898252e27c2831813f8568e52ed17e8843/README.md
> Using tables for better readability

- lit.go
- uspv/init.go
implement DNS lookups, have uspv deal with appending ports
> add DNS looksup and attempts

- .travis.yml
<a href="https://coveralls.io/github/Varunram/lit">Coveralls demo for branch</a>
goveralls package: https://github.com/mattn/goveralls
> Add coveralls integration

- powless/powless.go
This will monitor the hash of the highest block and set the dirty flag when it changes
> Set dirty when the highest blockhash changes

- portxo/portxo.go
- wallit/signsend.go
And don't consider unconfirmed tx's
> Move Fee Estimation to portxo

- qln/netio.go
> Remove unused locks

- coinparam/difficulty.go
- uspv/eight333.go
Do difficulty prediction in a specific branch the way btcd does it.
> Correct testnet diff prediction

- .travis.yml
- README.md
- test/lit_test_framework.py
- test/litnode.py
- test/test_basic.py
<a href="https://github.com/mit-dci/lit/blob/master/test/test_basic.py#L116">Line 116</a> in test_basic.py still seems to be causing problems. Commented it out for now.
> Fix Travis

- coinparam/bc2.go
- coinparam/bitcoin.go
- coinparam/difficulty.go
- coinparam/litecoin.go
- coinparam/register.go
- coinparam/vertcoin.go
- uspv/header.go
This PR fixes Vertcoin and Vertcoin testnet sync when using uspv rather than powless.
> Fix VTC and VTCTEST parameters for uspv

- uspv/header.go
This was preventing VTC main net from synchronizing via archival nodes
> Properly obey AssumeDiffBefore coinparam

- cmd/lit-af/chancmds.go
- cmd/lit-af/shell.go
- litrpc/towercmds.go
- qln/justicetx.go
Looks like all the work was already done in the branch :(. This serves as a nice interface to interact with the watchtower.
> Sync 'watchrework' onto master

- README.md
also delete --tip from readme for now
> [Trivial] Delete todo line regarding lit.conf

- README.md
- consts/consts.go
- litrpc/chancmds.go
- litrpc/walletcmds.go
- qln/buildtx.go
- qln/fund.go
- qln/pushpull.go
- wallit/dbio.go
- wallit/signsend.go
have all constants in consts/consts.go
and import wherever needed
> Add new subdirectory consts

- cmd/lit-af/autocomplete.go
- cmd/lit-af/chancmds.go
- cmd/lit-af/dlccmds.go
- cmd/lit-af/lit-af.go
- cmd/lit-af/netcmds.go
- cmd/lit-af/shell.go
- cmd/lit-af/walletcmds.go
Previously failed calls would hang forever. Now they timeout after 10 seconds.
> Add a timeout to RPC calls in lit-af of 10 seconds

- cmd/lit-af/lit-af.go
- cmd/lit-af/netcmds.go
- litrpc/netcmds.go
> resolve bug where first time lit-af opening gives a requestasync error

- cmd/lit-af/chancmds.go
- cmd/lit-af/dlccmds.go
- cmd/lit-af/netcmds.go
- cmd/lit-af/shell.go
- cmd/lit-af/walletcmds.go
Mostly find and replace type fixes, reduces code repetition a bit
> add two new functions and reduce code repetition

- WALKTHROUGH.md
Updated to use the new address format, command responses (like `con`), and explanation for support cointypes that was added since it was originally written.
> Updates to WALKTHROUGH.md.

- lndc/conn.go
- lndc/netio.go
- qln/msghandler.go
This was not yet merged into master. It's needed for DLC's with larger numbers of signatures.
> Increase max message size to 16MB (needed for DLC)

- cmd/lit-af/shell.go
- coinparam/register.go
I'm not sure what everyone thinks of the formatting for the cointypes, of course we can always change it.
> Added list of cointypes in help command.

- Makefile
- build/env.sh
> Add Makefile and env.sh

- uspv/init.go
in the case we do connect to bad nodes, disconnect and keep trying. Closes #133 
Basically the same stuff we do above, but can't reduce code repetition due to scope.
EDIT: added three new functions, no repetition.
> keep reconnecting in case we connect to spam nodes

- uspv/init.go
- uspv/msghandler.go
- uspv/spvcon.go
Really, we must `DialNode` in case we disconnect, but there's the problem of peers being stale when we try to reconnect, so might as well gather `listofNodes` again.
> Reconnect to other nodes if we disconnect from one

- uspv/header.go
- uspv/header_test.go
Switch to the chain containing more work from the longer chain mechanism that we follow currently.
> Switch to chain containing more work

- cmd/lit-af/shell.go
- qln/netio.go
To identify a channel to a peer by lit address
> Expose LIT address into peer list

- cmd/lit-af/shell.go
> format output, make things look nicer/colorful

- litrpc/API.md
No code changes made, although I'm looking for comments on the doc format itself.
> Added RPC API docs.

- lit.go
- powless/powless.go
- qln/init.go
- uspv/chainhook.go
- uspv/init.go
- uspv/spvcon.go
- wallit/init.go
Similarly to #202, proxy Wallits with the `--proxywallet` command line option.
> Proxy uspv and powless

- lndc/conn.go
Somehow when implementing the ipv4 / ipv6 support, the functionality to be able to connect to hostnames was lost. I used this in my dockerized test environments (connecting to `{adr}@lit01` for instance)
Previously, i was able to connect to`{lnaddr}@{hostname}[:port]`. But this no longer works since hostnames are not recognized as valid IPs. Which you can turn them into by resolving them.
Added code to resolve hostnames.
Was unable to test this with IPv6 (as I don't have a DNS returning IPv6 addresses). If anyone knows how I can test that, i'd be happy to hear. For IPv4 this works.
> Allows connecting to hostnames (again)

- coinparam/bitcoin.go
- coinparam/litecoin.go
Also make testnet3 coins not  `TestCoin`s
> Mark all regtest coins as TestCoins

- qln/break.go
Fixes #278, will fix listen's RPC timeout in an upcoming PR
> Set channel state to closed only after break tx is broadcast

- uspv/header.go
- uspv/init.go
Node sync is currently broken, this commit fixes that.
> Revert relevant parts of 628d5edae29dfdda5b69ff94b92a4c347e0302a2

- litrpc/chancmds.go
- lnutil/btclib_test.go
- powless/powless.go
- qln/dlc.go
- qln/dualfund.go
- qln/fund.go
- qln/msghandler.go
- uspv/hardmode.go
- uspv/mblock.go
- uspv/msghandler.go
- wallit/dbio.go
Very nit stuff, but apparently these things aren't considered good practice, so might as well remove them while we still can. Would be helpful to have some kind of precommit hook defined for this though.
> Make go vet happy

- consts/consts.go
- litrpc/chancmds.go
- lnutil/dlclib.go
- qln/dualfund.go
- qln/fund.go
- qln/htlc.go
- qln/justicetx.go
- qln/pushpull.go
- wallit/dbio.go
Intended as a fix for #309, might have missed some places, do let me know in comments if I have and I can add them.
> Standardize consts, use common fees

- cmd/lit-af/shell.go
> Make ls error out on invalid params

- test/test_combinators.py
The fees were changed (`consts.QcStateFee` = 10) and the tests don't reflect that.
> Fee constants were changed, test not adjusted

- litrpc/lndcproxy.go
- litrpc/lndcrpcclient.go
- lnutil/msglib.go
- qln/remotecontrol.go
Added code documentation to the remote control code for making it better understandable.
> Code documentation for remote control

- qln/msghandler.go
Add handlers for remote control for the new refactored code.
> Add handlers for remote control

- lit.go
- litinit.go
Change the config working part where we were working on a copy of the config instead of the actual one.
> Don't work on a copy of the config struct

- uspv/init.go
> Fix for #371

- Makefile
Fixed #378.  I got to that sooner than I expected.
> Fixed Makefile not respecting GO_BUILD_EX_ARGS

- cmd/lit-af/netcmds.go
- lit.go
- litrpc/netcmds.go
- lndc/listener.go
- lnp2p/events.go
- lnp2p/listen.go
- lnp2p/peermgr.go
- lnutil/tracker.go
- qln/autoconnect.go
- qln/netio.go
Doesn't make sense passing around a port with a colon, just pass the port and colonize where necessary. Also maybe need a constant for the default port..
> Ports should be of type int

- lndc/noise_test.go
- scripts/gotests.sh
- test/runtests.py
- test/testlib.py
Probably should have been in the last PR, oops.
Also this is a new PR made with the correct account.
>  Fixed the way the test framework supplied ports to Lit to use the new port formatting

- litrpc/lndcrpcclient.go
- lndc/noise_test.go
- scripts/gotests.sh
- test/runtests.py
- test/testlib.py
So our repo had a small reorg and we need to catch up to the chain with most work. Authorship preserved as was earlier. Please use the "Merge Commit" button and not the "Squash Commit" button since each commit has a different author.
> Add missing commits back

- db/lnbolt/peerdb.go
- lit.go
- lncore/peers.go
- lnp2p/listen.go
- lnp2p/peermgr.go
- qln/eventhandlers.go
- qln/netio.go
- test/itest_break.py
- test/itest_close.py
- test/itest_pushbreak.py
- test/itest_pushclose.py
- test/itest_reconnect.py
- test/runtests.py
- test/testlib.py
- test/tests.txt
https://github.com/mit-dci/lit/pull/384 was a PR that couldn't be added to the other list because of a merge conflict. This is #384 rebased unto current master. @delbonis please verify if this contains all changes. If not, you can push to this fork directly to implement changes.
> Rebase #384 onto master
